const feature = [
    {
        id: 12,
        title: "Onsen UI",
        category: "Category",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/Onsen-UI-Bes-react-component-library.png",
        githubStars: "8.2kk",
        githubFolks: "930",
        count: 0,
    },
    {
        id: 13,
        category: "Category",
        title: "React DesktopI",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/React-Desktop.png",
        githubStars: "8.9k",
        githubFolks: "468",
        count: 0,
    },
    {
        id: 14,
        category: "Category",
        title: "Grommet",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/Grommet.png",
        githubStars: "5k",
        githubFolks: "966",
        count: 0,
    },
    {
        id: 16,
        category: "Category",
        title: "React Materialize",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/react-materialize-best-react-component-library.png",
        githubStars: "1.3k",
        githubFolks: "314",
        count: 0,
    },
];

const popular = [
    {
        id: 12,
        title: "Onsen UI",
        category: "Category",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/Onsen-UI-Bes-react-component-library.png",
        githubStars: "8.2kk",
        githubFolks: "930",
        count: 0,
    },
    {
        id: 13,
        category: "Category",
        title: "React DesktopI",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/React-Desktop.png",
        githubStars: "8.9k",
        githubFolks: "468",
        count: 0,
    },
    {
        id: 14,
        category: "Category",
        title: "Grommet",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/Grommet.png",
        githubStars: "5k",
        githubFolks: "966",
        count: 0,
    },
    {
        id: 16,
        category: "Category",
        title: "React Materialize",
        content: "",
        img: "https://blog.digitalogy.co/wp-content/uploads/2020/12/react-materialize-best-react-component-library.png",
        githubStars: "1.3k",
        githubFolks: "314",
        count: 0,
    },
];

export default feature;
