const story = [
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 1,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: true,
    },
    {
        id: 2,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 3,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: true,
    },
    {
        id: 4,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 5,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.ibb.co/2jjg4Ny/cms-temp-article-19132712927086-removebg-preview.png",
        hasDoneInterview: false,
    },
];
export default story;
