const story = [
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.pinimg.com/originals/e7/7c/28/e77c28e5469926632b38531730ab4ac2.png",
    },
    {
        id: 1,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 2,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://e7.pngegg.com/pngimages/398/59/png-clipart-businessperson-graphy-woman-happy-women-photography-people-thumbnail.png",
    },
    {
        id: 3,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 4,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.pinimg.com/originals/e7/7c/28/e77c28e5469926632b38531730ab4ac2.png",
    },
    {
        id: 5,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://e7.pngegg.com/pngimages/398/59/png-clipart-businessperson-graphy-woman-happy-women-photography-people-thumbnail.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://thumbs.dreamstime.com/b/passport-photo-young-woman-blonde-neutral-looking-52876050.jpg",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.pinimg.com/originals/e7/7c/28/e77c28e5469926632b38531730ab4ac2.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://e7.pngegg.com/pngimages/398/59/png-clipart-businessperson-graphy-woman-happy-women-photography-people-thumbnail.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://thumbs.dreamstime.com/b/passport-photo-young-woman-blonde-neutral-looking-52876050.jpg",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.pinimg.com/originals/e7/7c/28/e77c28e5469926632b38531730ab4ac2.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://e7.pngegg.com/pngimages/398/59/png-clipart-businessperson-graphy-woman-happy-women-photography-people-thumbnail.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://thumbs.dreamstime.com/b/passport-photo-young-woman-blonde-neutral-looking-52876050.jpg",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://i.pinimg.com/originals/e7/7c/28/e77c28e5469926632b38531730ab4ac2.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://www.pngfind.com/pngs/m/119-1194181_business-women-business-woman-png-transparent-png.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://e7.pngegg.com/pngimages/398/59/png-clipart-businessperson-graphy-woman-happy-women-photography-people-thumbnail.png",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://thumbs.dreamstime.com/b/passport-photo-young-woman-blonde-neutral-looking-52876050.jpg",
    },
    {
        id: 0,
        category: "김민재",
        title: "플랫폼 개발팀",
        img: "https://thumbs.dreamstime.com/b/passport-photo-young-woman-blonde-neutral-looking-52876050.jpg",
    },
];
export default story;
